Repository belitradas/test-infra, pull requests merged in 2019-05, with the labels that each got.

#4 bleh!
  README.md
Labels: approved, lgtm, size/XS

#5 clean branches and other plugins
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#6 add needs-rebase
  prow/plugins.yaml
Labels: approved, lgtm, size/S

#8 try fix rebase
  prow/plugins.yaml
Labels: approved

#10 branch protection
  prow/config.yaml
Labels: approved, size/S

#11 fix
  prow/plugins.yaml
Labels: approved

#12 add context to tide
  prow/config.yaml
Labels: approved, size/XS

#13 blah
  README.md
  prow/config.yaml
Labels: approved, lgtm, size/S

#14 commit to test branch protection
  README.md
Labels: approved, lgtm, size/XS

#15 playing with branch protection and tide
  prow/config.yaml
Labels: approved, lgtm, size/S

#16 fix
  prow/config.yaml
Labels: approved

#17 ...
  prow/config.yaml
Labels: approved

#18 fix branch protection for now
  prow/config.yaml
Labels: approved, lgtm, size/M

#19 add job
  config/jobs/belitradas/test-infra/jobs.yaml
Labels: approved, lgtm, size/S

#20 bleh
  README.md
  config/jobs/belitradas/test-infra/jobs.yaml
  prow/config.yaml
Labels: approved, lgtm, size/S

#21 fixed job
  config/jobs/belitradas/test-infra/jobs.yaml
Labels: approved, lgtm, size/XS

#22 bleh
  README.md
  config/jobs/belitradas/test-infra/jobs.yaml
Labels: approved, size/XS

#23 no message
  config/jobs/belitradas/test-infra/jobs.yaml
Labels: approved, size/S

#24 fix the repo name... again
  config/jobs/belitradas/test-infra/jobs.yaml
  prow/config.yaml
Labels: approved, size/M

#25 no message
  README.md
  prow/config.yaml
Labels: approved, lgtm, size/M

#26 Feature/add manifests
  config/jobs/belitradas/test-infra/jobs.yaml
  prow/config.yaml
  prow/manifests/00-config.yaml
  prow/manifests/01-network-policy.yaml
  prow/manifests/02-starter.yaml
  prow/scripts/bucket.sh
  prow/scripts/validate-config.sh
Labels: approved, lgtm, size/XXL

#27 test presubmit job
  config/jobs/belitradas/test-infra/jobs.yaml
  prow/config.yaml
  prow/scripts/validate-config.sh
Labels: approved, lgtm, size/M

#28 added PR status to deck
  .gitignore
  prow/manifests/02-starter.yaml
Labels: approved, lgtm, size/S

#31 format and presubmit mandatory
  Makefile
  config/jobs/belitradas/test-infra/jobs.yaml
  dockerfiles/kubectl/dockerfile
Labels: approved, lgtm, size/L

#32 fixed serviceaccount, make presubmit mandatory and added postsubmit
  config/jobs/belitradas/test-infra/jobs.yaml
Labels: approved, size/S

#33 Added just some files to test jobs
  LICENSE
  README.md
  config/jobs/belitradas/test-infra/jobs.yaml
Labels: approved, size/L

#34 and more tests...
  README.md
Labels: approved, lgtm, size/XS

#35 run checks only if needed
  config/jobs/belitradas/test-infra/jobs.yaml
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#36 this shouldn't trigger manifests
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#37 do not need two replicas for deck... in theory
  prow/manifests/resources/00-starter.yaml
Labels: approved, lgtm, size/XS

#38 send metrics to pushgateway and collect with prometheus
  prow/config.yaml
  prow/manifests/resources/02-metrics.yaml
Labels: approved, lgtm, size/S

#39 test if prow can manage personal repos
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/M

#40 added jobs for kctx-manager
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  config/jobs/belitre/kctx-manager/belitre-kctx-manager-jobs.yaml
Labels: approved, lgtm, size/M

#41 dockerfile to buid with go cross-compile
  Makefile
  config/jobs/belitre/kctx-manager/belitre-kctx-manager-jobs.yaml
  dockerfiles/gobuilder/dockerfile
Labels: approved, lgtm, size/M

#42 docker container with checkconfig to test configs faster and added te…
  Makefile
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  config/jobs/belitre/kctx-manager/belitre-kctx-manager-jobs.yaml
  dockerfiles/checkconfig/dockerfile
Labels: approved, lgtm, size/M

#43 removed comments
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, size/M

#44 trigger job
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  prow/config.yaml
Labels: approved, do-not-merge/hold, size/XS

#45 gzip enabled for jobs
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#46 moved presubmits to config for now to make it easier to change them w…
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  dockerfiles/checkconfig/dockerfile
  prow/config.yaml
Labels: approved, lgtm, size/L

#47 back to its own file
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  config/jobs/belitre/kctx-manager/belitre-kctx-manager-jobs.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#48 removed comments
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  prow/config.yaml
Labels: approved, lgtm, size/XS

#49 commit to test presubmit job
  prow/config.yaml
Labels: approved, lgtm, size/XS

#50 spyglass settings
  prow/config.yaml
Labels: approved, lgtm, size/S

#51 Reduced size of pvc for ghproxy
  prow/manifests/init/00-config.yaml
  prow/manifests/resources/00-starter.yaml
Labels: approved, lgtm, size/XS

#53 Moved dockerfiles to different repo
  Makefile
  dockerfiles/checkconfig/dockerfile
  dockerfiles/gobuilder/dockerfile
  dockerfiles/kubectl/dockerfile
  prow/manifests/init/01-network-policy.yaml
Labels: approved, lgtm, size/M

#54 Feature/first dockerfiles job
  README.md
  config/jobs/belitradas/dockerfiles/belitradas-dockerfiles-jobs.yaml
Labels: approved, lgtm, size/M

#55 added jobs for dockerfiles repos
  config/jobs/belitradas/dockerfiles/belitradas-dockerfiles-jobs.yaml
Labels: approved, lgtm, size/L

#56 fix env vars for postsubmits
  config/jobs/belitradas/dockerfiles/belitradas-dockerfiles-jobs.yaml
Labels: approved, lgtm, size/S

#57 use images created with prow in dockerfiles repo
  config/jobs/belitradas/test-infra/belitradas-test-infra-jobs.yaml
  config/jobs/belitre/kctx-manager/belitre-kctx-manager-jobs.yaml
Labels: approved, lgtm, size/XS

#58 added labels and fixed postsubmits for dockerfiles
  config/jobs/belitradas/dockerfiles/belitradas-dockerfiles-jobs.yaml
  prow/labels.yaml
  prow/manifests/init/00-config.yaml
  prow/plugins.yaml
Labels: approved, size/XXL
